[package]
name = "dyn-product"
version = "0.1.0"
authors = ["Niumlaque <niumlaque@gmail.com>"]
description = "A crate that creates cartesian product of size determined at runtime."
edition = "2021"

license = "MIT"
repository = "https://github.com/niumlaque/dyn-product"
readme = "README.md"
